default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: instagram-clone-dev

test:
  <<: *default
  database: instagram-clone-test

production:
  <<: *default
  database: instagram-clone-pro
